version: '3.8'

services:
  laravel:
    build:
      context: .
      target: builder
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
